### ISSUE TITLE
[bug]: Selecting Typescript "No" still generates the plugin as Typescript

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/sdk-plugin#23]
### What version of `@strapi/blocks-react-renderer` are you using?

- Npm version
        - Node.js version: 10
        - React version: N/A
        - `@strapi/blocks-react-renderer` version: N/A
        - Browser: N/A

### What's Wrong?

When selection the options during plugin generation, selecting "N" to the typescript question is still generates the plugin as typescript:

![image](https://github.com/strapi/sdk-plugin/assets/8593673/8afd3255-9402-45e6-8772-94a0515ff2b4)

### To Reproduce

Run the command and select no on the typescript question

### Expected Behaviour

Should generate the plugin as javascript

**Comment by sanhup** [comment]
Similar issues. Also, for example, package.json has a reference to "source": "./admin/src/index.js" while the file is created as .ts. The content is valid js though, so I was able to use the plugin by manually renaming all files to .js.

Then I had another issue after building because inside strapi-server.js there is a reference to /dist/server, but the files reference inside /dist/server/index.js don't exist after building eg `const bootstrap = require("./bootstrap");` there is no ./bootstrap inside the build folder. I am not that familiar with buiding js vs ts so this mightith buiding js vs ts so this might be expected. Nevertheless it works if I point strapi-server.js directly to  be expected. Nevertheless it works if I change strapi-server.js content to `module.exports = require('./server/src');`. This probably not the way to go.

**Comment by innerdvations** [comment]
Fixed with #25
